### Get all contacts
GET http://localhost:3000/contacts
Content-Type: application/json

### Get a single contact by ID
# Replace <CONTACT_ID> with an actual MongoDB ObjectId from your database
GET http://localhost:3000/contacts/<CONTACT_ID>
Content-Type: application/json


//LocalHost

GET http://localhost:3000/contacts HTTP/1.1

GET http://localhost:3000/contacts/{id} HTTP/1.1

//Production Render

